package com.appcombo.ch341p;

/* This class is generated by JADX */
/* renamed from: com.appcombo.ch341p.R  reason: case insensitive filesystem */
public final class C0000R {

    /* renamed from: com.appcombo.ch341p.R$drawable */
    public static final class drawable {
        public static final int ship2_3 = 2130837504;
    }

    /* renamed from: com.appcombo.ch341p.R$layout */
    public static final class layout {
        public static final int ch341 = 2130903040;
        public static final int destfile = 2130903041;
        public static final int dialog = 2130903042;
        public static final int dialoghex = 2130903043;
        public static final int entersourceictype = 2130903044;
        public static final int entertargetictype = 2130903045;
        public static final int finished = 2130903046;
        public static final int ic24xx_series = 2130903047;
        public static final int ic25xxx_series = 2130903048;
        public static final int procedure1 = 2130903049;
        public static final int setup = 2130903050;
        public static final int sourcefile = 2130903051;
        public static final int summarize = 2130903052;
        public static final int tablelayout = 2130903053;
        public static final int temperature = 2130903054;
        public static final int warning = 2130903055;
        public static final int wbview = 2130903056;
    }

    /* renamed from: com.appcombo.ch341p.R$xml */
    public static final class xml {
        public static final int device_filter = 2130968576;
    }

    /* renamed from: com.appcombo.ch341p.R$string */
    public static final class string {
        public static final int title0 = 2131034112;
        public static final int title1 = 2131034113;
        public static final int title2 = 2131034114;
        public static final int title3 = 2131034115;
        public static final int baudrate_prompt = 2131034116;
        public static final int databit_prompt = 2131034117;
        public static final int parity_prompt = 2131034118;
        public static final int stopbit_prompt = 2131034119;
        public static final int flow_prompt = 2131034120;
        public static final int display_prompt = 2131034121;
        public static final int Setup = 2131034122;
        public static final int Send = 2131034123;
        public static final int ClrScr = 2131034124;
        public static final int Pause = 2131034125;
        public static final int Wakeup = 2131034126;
        public static final int PulseCnt = 2131034127;
        public static final int Copy = 2131034128;
        public static final int EraseDelete = 2131034129;
        public static final int DetectChip = 2131034130;
        public static final int Service = 2131034131;
        public static final int Application = 2131034132;
        public static final int DIY = 2131034133;
        public static final int Back = 2131034134;
        public static final int Next = 2131034135;
        public static final int Show = 2131034136;
        public static final int File = 2131034137;
        public static final int OK = 2131034138;
        public static final int Cancel = 2131034139;
        public static final int Purpose = 2131034140;
        public static final int Purpose1 = 2131034141;
        public static final int SelectSourceModel = 2131034142;
        public static final int SelectTargetModel = 2131034143;
        public static final int Temper = 2131034144;
        public static final int CorrectTemper = 2131034145;
        public static final int Refresh = 2131034146;
        public static final int Emissivity = 2131034147;
        public static final int Unit = 2131034148;
        public static final int Laser = 2131034149;
    }

    /* renamed from: com.appcombo.ch341p.R$array */
    public static final class array {
        public static final int baudrate_arrays = 2131099648;
        public static final int databit_arrays = 2131099649;
        public static final int parity_arrays = 2131099650;
        public static final int stopbit_arrays = 2131099651;
        public static final int flow_arrays = 2131099652;
        public static final int display_arrays = 2131099653;
    }

    /* renamed from: com.appcombo.ch341p.R$menu */
    public static final class menu {
        public static final int activity_action = 2131165184;
    }

    /* renamed from: com.appcombo.ch341p.R$id */
    public static final class id {
        public static final int Button02 = 2131230720;
        public static final int Button01 = 2131230721;
        public static final int Button03 = 2131230722;
        public static final int Button04 = 2131230723;
        public static final int intcount = 2131230724;
        public static final int ScrollView01 = 2131230725;
        public static final int msg = 2131230726;
        public static final int destfiletextView1 = 2131230727;
        public static final int destfileeditTextName = 2131230728;
        public static final int textView1 = 2131230729;
        public static final int editTextName = 2131230730;
        public static final int textView2 = 2131230731;
        public static final int editTextNum = 2131230732;
        public static final int textViewHex = 2131230733;
        public static final int editTextNum1 = 2131230734;
        public static final int sourceic_back = 2131230735;
        public static final int sourceic_textView1 = 2131230736;
        public static final int sourceic_button1 = 2131230737;
        public static final int sourceic_button2 = 2131230738;
        public static final int sourceic_button3 = 2131230739;
        public static final int targetic_back = 2131230740;
        public static final int targetic_textView1 = 2131230741;
        public static final int targetic_button1 = 2131230742;
        public static final int targetic_button2 = 2131230743;
        public static final int targetic_button3 = 2131230744;
        public static final int Finish_status = 2131230745;
        public static final int Finish_verify = 2131230746;
        public static final int Finish_again = 2131230747;
        public static final int Finish_exit = 2131230748;
        public static final int ic24_back = 2131230749;
        public static final int ic24_textView1 = 2131230750;
        public static final int ic24_textView2 = 2131230751;
        public static final int ic24_button1 = 2131230752;
        public static final int ic24_button2 = 2131230753;
        public static final int ic24_button3 = 2131230754;
        public static final int ic24_button4 = 2131230755;
        public static final int ic24_button5 = 2131230756;
        public static final int ic24_button6 = 2131230757;
        public static final int ic24_button7 = 2131230758;
        public static final int ic24_button8 = 2131230759;
        public static final int ic24_button9 = 2131230760;
        public static final int ic24_button10 = 2131230761;
        public static final int ic24_button11 = 2131230762;
        public static final int ic24_button12 = 2131230763;
        public static final int ic24_button13 = 2131230764;
        public static final int ic25_back = 2131230765;
        public static final int ic25_textView1 = 2131230766;
        public static final int ic25_textView2 = 2131230767;
        public static final int ic25_button1 = 2131230768;
        public static final int ic25_button2 = 2131230769;
        public static final int ic25_button3 = 2131230770;
        public static final int ic25_button4 = 2131230771;
        public static final int ic25_button5 = 2131230772;
        public static final int ic25_button6 = 2131230773;
        public static final int ic25_button7 = 2131230774;
        public static final int ic25_button8 = 2131230775;
        public static final int ic25_button9 = 2131230776;
        public static final int ic25_button10 = 2131230777;
        public static final int ic25_button11 = 2131230778;
        public static final int ic25_button12 = 2131230779;
        public static final int ic25_button13 = 2131230780;
        public static final int ic25_button14 = 2131230781;
        public static final int ic25_button15 = 2131230782;
        public static final int ic25_button16 = 2131230783;
        public static final int ic25_button17 = 2131230784;
        public static final int ic25_button18 = 2131230785;
        public static final int button1 = 2131230786;
        public static final int button2 = 2131230787;
        public static final int button3 = 2131230788;
        public static final int button4 = 2131230789;
        public static final int button5 = 2131230790;
        public static final int button6 = 2131230791;
        public static final int ScrollView02 = 2131230792;
        public static final int log = 2131230793;
        public static final int baud = 2131230794;
        public static final int spinner1 = 2131230795;
        public static final int databit = 2131230796;
        public static final int spinner2 = 2131230797;
        public static final int parity = 2131230798;
        public static final int spinner3 = 2131230799;
        public static final int stopbit = 2131230800;
        public static final int spinner4 = 2131230801;
        public static final int flow = 2131230802;
        public static final int spinner5 = 2131230803;
        public static final int display = 2131230804;
        public static final int spinner6 = 2131230805;
        public static final int SumSrc_textView1 = 2131230806;
        public static final int SumSrcModel_textView1 = 2131230807;
        public static final int SumDest_textView1 = 2131230808;
        public static final int SumDestModel_textView1 = 2131230809;
        public static final int Sum_back = 2131230810;
        public static final int Sum_OK = 2131230811;
        public static final int fillable_area = 2131230812;
        public static final int tableic_back = 2131230813;
        public static final int tableic_next = 2131230814;
        public static final int tableic_msg = 2131230815;
        public static final int tableic_fill = 2131230816;
        public static final int tableic_addr = 2131230817;
        public static final int fillable_area0 = 2131230818;
        public static final int tablehead_part = 2131230819;
        public static final int scrollable_tb = 2131230820;
        public static final int tablescrollable_part = 2131230821;
        public static final int Temp_textView1 = 2131230822;
        public static final int Temp_edittext = 2131230823;
        public static final int Temp_textView2 = 2131230824;
        public static final int Temp_button1 = 2131230825;
        public static final int Temp_button2 = 2131230826;
        public static final int Temp_button3 = 2131230827;
        public static final int about0 = 2131230828;
        public static final int about1 = 2131230829;
        public static final int about2 = 2131230830;
        public static final int about3 = 2131230831;
        public static final int about4 = 2131230832;
        public static final int ButtonWarning = 2131230833;
        public static final int webview = 2131230834;
        public static final int action_warning = 2131230835;
        public static final int action_about = 2131230836;
        public static final int action_exit = 2131230837;
    }
}
